### ISSUE TITLE
Hidden files like .gitignore

### ISSUE THREAD

**Issue by tanders** [stacksmith/trivial-project#1]
Dear stacksmith,

Your project trivial-project is neat, thanks for that!

However, what about supporting hidden files like .gitignore in custom templates? 

Currently hidden files are not only ignored, but even cause an error in function filename-action. 

Best,
Torsten

**Comment by stacksmith** [comment]
@tanders - I noticed that a while ago, with .gitignore. 

 I fixed it to process hidden files same as the rest (ignoring .local.tp specifically for now, which is not precisely correct since it could be named something else via make-project parameter `:TP-LOCAL-CONFIG-FILENAME`)

So it works, but I should make it right later.r.

**Comment by tanders** [comment]
I can confirm that .gitignore in the template is now copied too.

**Comment by stacksmith** [comment]
Good.
