### ISSUE TITLE
:DEPENDS-ON better nil by default?

### ISSUE THREAD

**Issue by tanders** [stacksmith/trivial-project#2]
In the default settings, :DEPENDS-ON is an empty string, resulting in an not-working ASDF system. This should better be nil.

Currently this can be set as "()", but perhaps you also want to support plain Lisp values (such as nil), not only strings.

Best,
Torsten

**Comment by stacksmith** [comment]
@tanders, thanks for the kind words and bug reports

My mistake.  Fixed. (I was vascillating on where the parens should go and forgot...)

The .asd template should read  `:depends-on (~~DEPENDS-ON~~)`

.local.tp initializes it with a "".  `make-project` may change it to an appropriate string.

The depends-on parameter is a string, because it is substituted with the regex engine, and may itself contain `~~xx~~` variables that will be expanded.

Please let me know if the fix works for you.

**Comment by tanders** [comment]
I am using the file ~/.trivial-project-global.tp, and when I set there :DEPENDS-ON  "()" the resulting ASDF file is fine.

**Comment by stacksmith** [comment]
The way I have in the repo, the local default "" gets spliced into the template's `(~~DEPENDS-ON~~)`, so the template provides :depends-on () -- which works.  Now you can specify `(make-project :name "crap" :depends-on ":a :b :c")`

The way you have it (I think), the template provides `:DEPENDS-ON ~~DEPENDS-ON~~`, which the global fills in with `()`.  If you want to specify dependencies, you now have to include parens around the list in the string.

Either way is fine - but I prefer not placing parens, since it's a string.  It's also the way everyone else's setup will be.  But if you like the other way that's fine.

The global file is there mostly so that you can put your name, email address and such, and it will work with different templates.  You should probably fix the template to the way you want it, and leave the global file out of it unless you mean it.

**Comment by tanders** [comment]
When in ~/.trivial-project-global.tp I set :DEPENDS-ON to () as you suggest in your comment at the top of the README I get an error. When :DEPENDS-ON is "" I get a project that ASDF cannot load, because there is no value specified for that keyword. :DEPENDS-ON "()" currently works.

Torsten

**Comment by stacksmith** [comment]
OK, I think you misunderstood my suggestion... I can see why, so instead:
1) Do not use .trivial-project-global.tp for anything other than your name, and license if you always use the same one  (constants, not defaults).  Do not use it to set `:DEPENDS-ON` or any other defaults; it may work but it is wrong and confusing.
2) Just make your system match this repo, or we will go in circles forever.  The local file should set the default `:depends-on  ""`, the .asd template should read `:depends-on  (~~DEPENDS-ON~~)`, and the global file should not mention it.
3) To specify dependencies in make-project, do not use parens.  It should look something like `:depends-on ":cffi :cl-ppcre"`
4) There is a reason for not using parens, even if it seems to make more sense.  You may want to include a permanent dependency in the template, and be able to add some more dependencies in the make-project invocation.  If you parenthesize the latter, you will not be able to do that.  The way I do it, the template will say `:depends-on (:permanent-dependency ~~DEPENDS-ON~~)`, so invocation dependencies will get spliced right in.

That should resolve the problems. 

TRIVIAL-PROJECT is very simple, but since everything is configurable, there are many ways to do the same thing.  Until you feel really certain about how things work, it's better not to do it in the opposite way from everyone else.
